In [3]:
import numpy as np

In [6]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [8]:
print(x[0])

1


In [9]:
y=np.array(['one','two','three','four' ,"five"])
print(y)

['one' 'two' 'three' 'four' 'five']


In [11]:
y=np.array(['one','two','three','four' ,"five"])
print(y[3])

four


In [12]:
y=np.array(['one','two','three','four' ,"five"])
print(y[2])

three


In [15]:
z=np.array([1,2,3,],[4,5,6])
print(z)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
# Pandas


In [16]:
import pandas as pd

In [19]:
x=pd.DataFrame([1,2,3])
print(x)

   0
0  1
1  2
2  3


In [20]:
x=pd.Series([1,2,3,4])
print(x)

0    1
1    2
2    3
3    4
dtype: int64


In [21]:
x=pd.Series([5,2,3,6])
print(x)

0    5
1    2
2    3
3    6
dtype: int64


# The Series in Pandas

In [22]:
mySeries=pd.Series([1,-3,5,-20])
print(mySeries)

0     1
1    -3
2     5
3   -20
dtype: int64


In [28]:
mySeries2=pd.Series([1,-3,5,-20], index=['a','b','c','d'])
print(mySeries2)

a     1
b    -3
c     5
d   -20
dtype: int64


In [30]:
m=mySeries2.values
print(m)

[  1  -3   5 -20]


In [31]:
m=mySeries2.index
print(m)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [32]:
m=mySeries2[2]
print(m)

5


In [33]:
m=mySeries2[0:2]
print(m)

a    1
b   -3
dtype: int64


In [35]:
m=mySeries2['b']
print(m)

-3


In [37]:
m=mySeries2[['b','c']]
print(m)

b   -3
c    5
dtype: int64


In [39]:
m=mySeries2[2]
print(m)

5


In [40]:
m=mySeries2[0:2]
print(m)

a    1
b   -3
dtype: int64


In [41]:
m=mySeries2['b']
print(m)

-3


In [44]:
m=mySeries2[['a','b']]
print(m)

a    1
b   -3
dtype: int64


In [45]:
mySeries2['c']=200
print(mySeries2)

a      1
b     -3
c    200
d    -20
dtype: int64


# We can create a Series object from an existing array as follows:


In [46]:
myarray=np.array([1,2,3,4])
myseries3=pd.Series(myarray)
myseries3

0    1
1    2
2    3
3    4
dtype: int32

In [47]:
myseries3[myseries3>2]

2    3
3    4
dtype: int32

In [51]:
myseries3[myseries3<2]

0    1
dtype: int32

In [49]:
myseries3[myseries3>=2]

1    2
2    3
3    4
dtype: int32

In [55]:
myseries3[myseries3<=2]

0    1
1    2
dtype: int32

In [53]:
myseries3[myseries3%2]

1    2
0    1
1    2
0    1
dtype: int32

In [54]:
np.log(myseries3)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
dtype: float64

In [57]:
np.log(mySeries2)

C:\Users\itoro_bo9ber6\anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


a    0.000000
b         NaN
c    5.298317
d         NaN
dtype: float64

In [58]:
np.square(mySeries2)

a        1
b        9
c    40000
d      400
dtype: int64

In [60]:
np.square(mySeries3)

AttributeError: module 'numpy' has no attribute 'Square'

In [61]:
np.indices(myseries3)

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]],



       [[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]],



       [[[[0, 0, 0, 0],
          [1, 1, 1, 1],
          [2, 2, 2, 2]],

         [[0, 0, 0, 0],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]]],



       [[[[0, 1, 2, 3],
          [0, 1, 2, 3],
          [0, 1, 2, 3]],

         [[0, 1, 2, 3],
          [0, 1, 2, 3],
          [0, 1, 2, 3]]]]])

In [63]:
np.cos(myseries3)

0    0.540302
1   -0.416147
2   -0.989992
3   -0.653644
dtype: float64

In [64]:
np.diff(myseries3)

array([1, 1, 1])

In [65]:
np.sin(myseries3)

0    0.841471
1    0.909297
2    0.141120
3   -0.756802
dtype: float64

In [66]:
np.tan(myseries3)

0    1.557408
1   -2.185040
2   -0.142547
3    1.157821
dtype: float64

# We can a the Series, mycolor to perform some common operations that can be applied to a Series
Example: SomeColors

In [71]:
mycolours=pd.Series([1,2,3,4,5,4,3,2,1], index=['white', 'black','green','blue','yellow', 'blue','green','black','white'])
mycolours

white     1
black     2
green     3
blue      4
yellow    5
blue      4
green     3
black     2
white     1
dtype: int64

In [68]:
mycolours.unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [70]:
mycolours.value_counts()

1    2
2    2
3    2
4    2
5    1
dtype: int64

In [72]:
mycolours.isin([5,7])

white     False
black     False
green     False
blue      False
yellow     True
blue      False
green     False
black     False
white     False
dtype: bool

In [73]:
mycolours.isin([6])

white     False
black     False
green     False
blue      False
yellow    False
blue      False
green     False
black     False
white     False
dtype: bool

In [74]:
mycolours.isin([2])

white     False
black      True
green     False
blue      False
yellow    False
blue      False
green     False
black      True
white     False
dtype: bool

In [75]:
mycolours.isin([5,7])

white     False
black     False
green     False
blue      False
yellow     True
blue      False
green     False
black     False
white     False
dtype: bool

# To get filtered Series

In [76]:
mycolours[mycolours.isin([5,7])]

yellow    5
dtype: int64

In [79]:
mycolours[mycolours.isin([3,5,8])]

green     3
yellow    5
green     3
dtype: int64

In [80]:
mycolours[mycolours.isin([3,5,7,9])]

green     3
yellow    5
green     3
dtype: int64

In [81]:
mycolours[mycolours.isin([2,1,4])]

white    1
black    2
blue     4
blue     4
black    2
white    1
dtype: int64

# Creating Series from an already defined dictionary


In [83]:
mydict={'White':200, 'Black':300, 'Red':500, 'Green':1000}
myseries=pd.Series(mydict)
myseries

White     200
Black     300
Red       500
Green    1000
dtype: int64

# The DataFrame

In [84]:
import pandas as pd.Series

SyntaxError: invalid syntax (<ipython-input-84-9b1ec7ebf853>, line 1)

In [94]:
mydata={'Employee Name':['Jaja', 'Edidiong','Itoro','Ubong','Uduak'],
       'Specialization':['Python', 'Data Science', 'Data preparation', 'Data Analysis','Machine Learning'],
       'Qualification':['FSLC', 'SSCE', 'B.Sc.', 'MSc.', 'PhD'],
       'Experience (in years)':[3,5,8,2,4],
       'Gender': ['M','F','M','F','M'],
        'Address':['Uyo','Ikot Abasi','Ini','Ibesikpo','Uruan'],
       'Phone':['08024687391', '08034567899','070344556677','080266777664','090234444400'],
        'Sports':['Basket ball','Volleyball','Foot ball','Swimming','Skiing'],
        'Religion':['Christianity','Islam','Budhism','Judaism','Traditionalist'],
        'Marital Status':['Married', 'Single','Complicated','Divorced','Married'],
       'Best Food':['Jellof Rice', 'Boiled Yam with Fish Stew', 'White Soup with Eba','Coconut Rice','Edikang ikong with Plain Rice'],}
myframe=pd.DataFrame(mydata)# note capital D and F in DataFrame()constructor
myframe

Employee Name    Specialization Qualification  Experience (in years) Gender  \
0          Jaja            Python          FSLC                      3      M   
1      Edidiong      Data Science          SSCE                      5      F   
2         Itoro  Data preparation         B.Sc.                      8      M   
3         Ubong     Data Analysis          MSc.                      2      F   
4         Uduak  Machine Learning           PhD                      4      M   

      Address         Phone       Sports        Religion Marital Status  \
0         Uyo   08024687391  Basket ball    Christianity        Married   
1  Ikot Abasi   08034567899   Volleyball           Islam         Single   
2         Ini  070344556677    Foot ball         Budhism    Complicated   
3    Ibesikpo  080266777664     Swimming         Judaism       Divorced   
4       Uruan  090234444400       Skiing  Traditionalist        Married   

                       Best Food  
0                    Jellof Rice  
1      Boiled Yam with Fish Stew  
2            White Soup with Eba  
3                   Coconut Rice  
4  Edikang ikong with Plain Rice

# We can select an information from our DataFrame in any order/ Slicing

In [95]:
myframe2=pd.DataFrame(mydata, columns=['Experience (in years)', 'Employee Name', 'Phone', 'Religion'])
myframe2

Experience (in years) Employee Name         Phone        Religion
0                      3          Jaja   08024687391    Christianity
1                      5      Edidiong   08034567899           Islam
2                      8         Itoro  070344556677         Budhism
3                      2         Ubong  080266777664         Judaism
4                      4         Uduak  090234444400  Traditionalist

In [98]:
myframe3=pd.DataFrame(mydata, columns=['Best Food', 'Employee Name', 'Phone', 'Marital Status','Sports','Qualification'])
myframe3

Best Food Employee Name         Phone Marital Status  \
0                    Jellof Rice          Jaja   08024687391        Married   
1      Boiled Yam with Fish Stew      Edidiong   08034567899         Single   
2            White Soup with Eba         Itoro  070344556677    Complicated   
3                   Coconut Rice         Ubong  080266777664       Divorced   
4  Edikang ikong with Plain Rice         Uduak  090234444400        Married   

        Sports Qualification  
0  Basket ball          FSLC  
1   Volleyball          SSCE  
2    Foot ball         B.Sc.  
3     Swimming          MSc.  
4       Skiing           PhD

In [103]:
myframe4=pd.DataFrame(mydata, index=['I', 'II', 'III', 'IV','V'])
myframe4

Employee Name    Specialization Qualification  Experience (in years)  \
I            Jaja            Python          FSLC                      3   
II       Edidiong      Data Science          SSCE                      5   
III         Itoro  Data preparation         B.Sc.                      8   
IV          Ubong     Data Analysis          MSc.                      2   
V           Uduak  Machine Learning           PhD                      4   

    Gender     Address         Phone       Sports        Religion  \
I        M         Uyo   08024687391  Basket ball    Christianity   
II       F  Ikot Abasi   08034567899   Volleyball           Islam   
III      M         Ini  070344556677    Foot ball         Budhism   
IV       F    Ibesikpo  080266777664     Swimming         Judaism   
V        M       Uruan  090234444400       Skiing  Traditionalist   

    Marital Status                      Best Food  
I          Married                    Jellof Rice  
II          Single      Boiled Yam with Fish Stew  
III    Complicated            White Soup with Eba  
IV        Divorced                   Coconut Rice  
V          Married  Edikang ikong with Plain Rice

In [105]:
myframe5=pd.DataFrame(mydata, index=['1', '2', '3','4','5'])
myframe5

Employee Name    Specialization Qualification  Experience (in years) Gender  \
1          Jaja            Python          FSLC                      3      M   
2      Edidiong      Data Science          SSCE                      5      F   
3         Itoro  Data preparation         B.Sc.                      8      M   
4         Ubong     Data Analysis          MSc.                      2      F   
5         Uduak  Machine Learning           PhD                      4      M   

      Address         Phone       Sports        Religion Marital Status  \
1         Uyo   08024687391  Basket ball    Christianity        Married   
2  Ikot Abasi   08034567899   Volleyball           Islam         Single   
3         Ini  070344556677    Foot ball         Budhism    Complicated   
4    Ibesikpo  080266777664     Swimming         Judaism       Divorced   
5       Uruan  090234444400       Skiing  Traditionalist        Married   

                       Best Food  
1                    Jellof Rice  
2      Boiled Yam with Fish Stew  
3            White Soup with Eba  
4                   Coconut Rice  
5  Edikang ikong with Plain Rice

In [109]:
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 2-dimensional array


In [120]:
myframe4=pd.DataFrame(np.arange(15).reshape((3,5)),
index=['row0','row1','row2'], columns=['col1','col2','col3','col4','col5'])
myframe4

col1  col2  col3  col4  col5
row0     0     1     2     3     4
row1     5     6     7     8     9
row2    10    11    12    13    14